# Generated by Django 5.0.6 on 2026-06-30 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('driver_name', models.CharField(max_length=255)),
                ('vehicle_plate', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['device_id'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_level', models.IntegerField(choices=[(0, 'Safe'), (1, 'Caution'), (2, 'Warning'), (3, 'Danger')])),
                ('alarm_msg', models.TextField()),
                ('perclos', models.FloatField()),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lon', models.FloatField(blank=True, null=True)),
                ('gps_speed', models.FloatField(blank=True, null=True)),
                ('cabin_temp', models.FloatField(blank=True, null=True)),
                ('cabin_humidity', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dms.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LiveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_level', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lon', models.FloatField(blank=True, null=True)),
                ('gps_speed', models.FloatField(blank=True, null=True)),
                ('perclos', models.FloatField(default=0.0)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live', to='dms.device')),
            ],
        ),
    ]
